[package]
name = "rendy-chain"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]
edition = "2018"
repository = "https://github.com/omni-viral/rendy"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/rendy-chain"
keywords = ["graphics", "gfx-hal", "rendy"]
categories = ["rendering"]
description = "Rendy's node synchronization tool"

[dependencies]
gfx-hal = { version = "0.1", path = "../../gfx/src/hal" }
fnv = "1.0"
log = "0.4"
